version: 2

models:
  - name: stg_local_bike__brands
    description: "This model contains information about all the brands sold in the shops."
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand."
        tests:
          - unique
          - not_null
      - name: brand_name
        description: "Name of each brand"

  - name: stg_local_bike__categories
    description: "This model contains information about categories of products."
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category of products."
        tests:
          - unique
          - not_null
      - name: category_name
        description: "Name of each category of product"

  - name: stg_local_bike__customers
    description: "This model contains information about customers"
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
          - unique
          - not_null
      - name: customer_city
        description: "City referenced for each customer. Renamed from city to customer_city"
      - name: customer_full_address
        description: "street, zip_code, city, state concatenated to get full adress."

  - name: stg_local_bike__order_items
    description: "This model contains information about items in each order including quantity, price and discount."
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each item, generated by concatenating order_id and product_id."
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key linking to the corresponding order passed."
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__order_items
              to: ref('stg_local_bike__orders')
              field: order_id
      - name: product_id
        description: "Foreign key linking to each product in the product table."
        tests:
          - relationships:
              name: product_id_foreign_key_in_stg_local_bike__order_items
              to: ref('stg_local_bike__products')
              field: product_id
      - name: item_price
        description: "Price column name changed from list_price to item_price."
      - name: item_quantity
        description: "Quantity of items ordered in each order"
      - name: total_order_item_amount
        description: "The total amount for this order item, calculated as (list_price * quantity) * (1 - discount)."
      
  - name: stg_local_bike__orders
    description: "This model contains information about orders including order status and discount information."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key linking to the customer who passed the order."
        tests:
          - relationships:
              name: customer_id_foreign_key_in_stg_local_bike__orders
              to: ref('stg_local_bike__customers')
              field: customer_id
      - name: order_status
        description: "Status of each order, int transformed into string to describe the status more precisely."
        tests:
          - accepted_values:
              name: accepted_values_order_status
              values: ['Processed', 'Shipped', 'Delivered', 'Returned / Lost']
      - name: order_date
        description: "Date when the order was made."
      - name: store_id
        description: "Foreign key linking the order to the store from which it was issued."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_local_bike__orders
              to: ref('stg_local_bike__stores')
              field: store_id

  - name: stg_local_bike__products
    description: "This model contains basic information about each product : name, brand, category, year of the model and price."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Name of the product."
      - name: brand_id
        description: "Foreign key linking the brand of the product."
        tests:
          - relationships:
              name: brand_id_foreign_key_in_stg_local_bike__products
              to: ref('stg_local_bike__brands')
              field: brand_id
      - name: category_id
        description: "Foreign key linking the category of the product."
        tests:
          - relationships:
              name: category_id_foreign_key_in_stg_local_bike__products
              to: ref('stg_local_bike__categories')
              field: category_id
      - name: model_year
        description: "Production year of the product."
      - name: item_price
        description: "list_price renamed item_price."

  - name: stg_local_bike__stocks
    description: "This model contains user-related information, including where they live."
    columns:
      - name: store_id
        description: "Foreign key linking to the store."
      - name: product_id
        description: "Foreign key linking to each product."
      - name: item_quantity_in_stock
        description: "Quantity of product in stock in each store."
 
  - name: stg_local_bike__stores
    description: "This model contains stores information including their location."
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each store."
        tests:
          - unique
          - not_null
      - name: store_name
        description: "Name of each store."
      - name: store_city
        description: "City of each store. Renamed from city to store_city"




#  - name: order_status
#        description: "The current status of the order."
#        tests:
#          - accepted_values:
#              name: accepted_values_order_status
#              values: ['created', 'shipped', 'approved', 'canceled', 'invoiced', 'delivered', 'processing', 'unavailable']Procc


